.TH "ArgumentParser" 3 "Tue Feb 15 2022" "log4python" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArgumentParser
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBparse_arguments\fP ()"
.br
.ti -1c
.RI "def \fBcheck_environment\fP (args)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
@package docstring
Documentation for this module\&.
 
More details\&.

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def ArgumentParser\&.check_environment ( args)"

.SS "def ArgumentParser\&.parse_arguments ()"

.PP
.nf
Documentation for a function\&.

More details\&.

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for log4python from the source code\&.
