.TH "src/PiMotionSensor.py" 3 "Tue Feb 15 2022" "log4python" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/PiMotionSensor.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPiMotionSensor\&.MachineState\fP"
.br
.ti -1c
.RI "class \fBPiMotionSensor\&.PiMotionSensor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPiMotionSensor\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPiMotionSensor\&.args\fP = parse_arguments()"
.br
.ti -1c
.RI "\fBPiMotionSensor\&.sensor\fP = PiMotionSensor(args)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4python from the source code\&.
