.TH "PiMotionSensor.MachineState" 3 "Tue Feb 15 2022" "log4python" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PiMotionSensor.MachineState
.SH SYNOPSIS
.br
.PP
.PP
Inherits Enum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBOFF\fP = 0"
.br
.ti -1c
.RI "int \fBON\fP = 1"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int PiMotionSensor\&.MachineState\&.OFF = 0\fC [static]\fP"

.SS "int PiMotionSensor\&.MachineState\&.ON = 1\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for log4python from the source code\&.
