.TH "PiMotionSensor.PiMotionSensor" 3 "Tue Feb 15 2022" "log4python" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PiMotionSensor.PiMotionSensor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPiSensor\&.PiSensor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBargs\fP)"
.br
.ti -1c
.RI "def \fBminute_changed\fP (self, now)"
.br
.ti -1c
.RI "def \fBhour_changed\fP (self, now)"
.br
.ti -1c
.RI "def \fBday_changed\fP (self, now)"
.br
.ti -1c
.RI "def \fBmotion_start\fP (self)"
.br
.ti -1c
.RI "def \fBmotion_end\fP (self)"
.br
.ti -1c
.RI "def \fBsetup\fP (self)"
.br
.ti -1c
.RI "def \fBprocess_event\fP (self, item, now)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdata\fP"
.br
.ti -1c
.RI "\fBsensor\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def PiMotionSensor\&.PiMotionSensor\&.__init__ ( self,  args)"

.PP
Reimplemented from \fBPiSensor\&.PiSensor\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def PiMotionSensor\&.PiMotionSensor\&.day_changed ( self,  now)"

.PP
Reimplemented from \fBPiSensor\&.PiSensor\fP\&.
.SS "def PiMotionSensor\&.PiMotionSensor\&.hour_changed ( self,  now)"

.PP
Reimplemented from \fBPiSensor\&.PiSensor\fP\&.
.SS "def PiMotionSensor\&.PiMotionSensor\&.minute_changed ( self,  now)"

.PP
Reimplemented from \fBPiSensor\&.PiSensor\fP\&.
.SS "def PiMotionSensor\&.PiMotionSensor\&.motion_end ( self)"

.SS "def PiMotionSensor\&.PiMotionSensor\&.motion_start ( self)"

.SS "def PiMotionSensor\&.PiMotionSensor\&.process_event ( self,  item,  now)"

.PP
Reimplemented from \fBPiSensor\&.PiSensor\fP\&.
.SS "def PiMotionSensor\&.PiMotionSensor\&.setup ( self)"

.PP
Reimplemented from \fBPiSensor\&.PiSensor\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "PiMotionSensor\&.PiMotionSensor\&.data"

.SS "PiMotionSensor\&.PiMotionSensor\&.sensor"


.SH "Author"
.PP 
Generated automatically by Doxygen for log4python from the source code\&.
