.TH "PiMotionSensor" 3 "Tue Feb 15 2022" "log4python" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PiMotionSensor
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMachineState\fP"
.br
.ti -1c
.RI "class \fBPiMotionSensor\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBargs\fP = parse_arguments()"
.br
.ti -1c
.RI "\fBsensor\fP = \fBPiMotionSensor\fP(\fBargs\fP)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "PiMotionSensor\&.args = parse_arguments()"

.SS "PiMotionSensor\&.sensor = \fBPiMotionSensor\fP(\fBargs\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4python from the source code\&.
