.TH "src/PiSensor.py" 3 "Tue Feb 15 2022" "log4python" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/PiSensor.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPiSensor\&.PiSensor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPiSensor\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPiSensor\&.args\fP = parse_arguments()"
.br
.ti -1c
.RI "\fBPiSensor\&.sensor\fP = PiSensor(args)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4python from the source code\&.
