.TH "PiSensor" 3 "Tue Feb 15 2022" "log4python" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PiSensor
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPiSensor\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBargs\fP = parse_arguments()"
.br
.ti -1c
.RI "\fBsensor\fP = \fBPiSensor\fP(\fBargs\fP)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "PiSensor\&.args = parse_arguments()"

.SS "PiSensor\&.sensor = \fBPiSensor\fP(\fBargs\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4python from the source code\&.
