.TH "SaveHandlers.ConsoleHandler" 3 "Mon Feb 14 2022" "log4python" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaveHandlers.ConsoleHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSaveHandlers\&.SaveHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBargs\fP)"
.br
.ti -1c
.RI "def \fBsave\fP (self, data)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBargs\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def SaveHandlers\&.ConsoleHandler\&.__init__ ( self,  args)"

.SH "Member Function Documentation"
.PP 
.SS "def SaveHandlers\&.ConsoleHandler\&.save ( self,  data)"

.PP
Reimplemented from \fBSaveHandlers\&.SaveHandler\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "SaveHandlers\&.ConsoleHandler\&.args"


.SH "Author"
.PP 
Generated automatically by Doxygen for log4python from the source code\&.
