.TH "SaveHandlers.SaveHandler" 3 "Mon Feb 14 2022" "log4python" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaveHandlers.SaveHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSaveHandlers\&.ConsoleHandler\fP, and \fBSaveHandlers\&.FileSaveHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsave\fP (self, \fBargs\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "def SaveHandlers\&.SaveHandler\&.save ( self,  args)"

.PP
Reimplemented in \fBSaveHandlers\&.FileSaveHandler\fP, and \fBSaveHandlers\&.ConsoleHandler\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for log4python from the source code\&.
