.TH "src/SaveHandlers.c" 3 "Tue Feb 15 2022" "log4python" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/SaveHandlers.c
.SH SYNOPSIS
.br
.PP
\fC#include 'Python\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPY_SSIZE_T_CLEAN\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PY_SSIZE_T_CLEAN"

.SH "Author"
.PP 
Generated automatically by Doxygen for log4python from the source code\&.
