.TH "src/SaveHandlers.py" 3 "Mon Feb 14 2022" "log4python" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/SaveHandlers.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSaveHandlers\&.SaveHandler\fP"
.br
.ti -1c
.RI "class \fBSaveHandlers\&.FileSaveHandler\fP"
.br
.ti -1c
.RI "class \fBSaveHandlers\&.ConsoleHandler\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSaveHandlers\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dictionary \fBSaveHandlers\&.SaveHandlers\fP"
.br
.ti -1c
.RI "\fBSaveHandlers\&.args\fP = parse_arguments()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for log4python from the source code\&.
