.TH "SensorWatch.Application" 3 "Mon Feb 14 2022" "log4python" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SensorWatch.Application
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBcreate_sensor\fP (self)"
.br
.ti -1c
.RI "def \fBread_configuration\fP (self)"
.br
.ti -1c
.RI "def \fBparse_arguments\fP (self)"
.br
.ti -1c
.RI "def \fBcheck_env\fP (self)"
.br
.ti -1c
.RI "def \fBsignal_handler\fP (self, signum, frame)"
.br
.ti -1c
.RI "def \fBsignal_setup\fP (self)"
.br
.ti -1c
.RI "def \fBrun\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBargs\fP"
.br
.ti -1c
.RI "\fBsensor\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def SensorWatch\&.Application\&.__init__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "def SensorWatch\&.Application\&.check_env ( self)"

.SS "def SensorWatch\&.Application\&.create_sensor ( self)"

.SS "def SensorWatch\&.Application\&.parse_arguments ( self)"

.SS "def SensorWatch\&.Application\&.read_configuration ( self)"

.SS "def SensorWatch\&.Application\&.run ( self)"

.SS "def SensorWatch\&.Application\&.signal_handler ( self,  signum,  frame)"

.SS "def SensorWatch\&.Application\&.signal_setup ( self)"

.SH "Member Data Documentation"
.PP 
.SS "SensorWatch\&.Application\&.args"

.SS "SensorWatch\&.Application\&.sensor"


.SH "Author"
.PP 
Generated automatically by Doxygen for log4python from the source code\&.
